### PR TITLE
[irods/irods 7152] Refactor lib.py resource functions (main)

### PR DESCRIPTION
**Pull request by Nishant2022**
Refactor lib.py functions to match those in the main iRODS repo.

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look good.

Consider adjusting the commit message to say something about updating the resource functions to match changes in lib.py.

For example ...
```
[irods/irods 7152] Updated use of resource functions in lib.py.
```

**Comment by JustinKyleJames** [comment]
This explains why the tests against the tip of main were failing on these methods.  Thanks for the update.

@Nishant2022 Do you need me to run this through S3 testing?

**Comment by JustinKyleJames** [comment]
> This explains why the tests against the tip of main were failing on these methods. Thanks for the update.
> 
> @Nishant2022 Do you need me to run this through S3 testing?

I kicked off some testing for this.

**Comment by korydraughn** [comment]
@JustinKyleJames Great. Thanks for running the tests for this.

Please leave a comment about the test results once complete.

**Comment by JustinKyleJames** [comment]
I ran the Test_S3_NoCache_V4 and Test_Compound_With_S3_Resource test suites and they both passed.

**Review by korydraughn — APPROVED** [review]
@JustinKyleJames Excellent!

@Nishant2022 Please adjust the commit message if you haven't already and add the pound.

**Review by alanking — APPROVED** [review]

**Pull request merged**
