### PR TITLE
Add tests for data objects stuck in locked status, prevent nullptr dereference (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #2092
Addresses #2095
Addresses https://github.com/irods/irods/issues/6154
Addresses https://github.com/irods/irods/issues/6479
Addresses https://github.com/irods/irods/issues/6880

Companion PR: https://github.com/irods/irods/pull/6905
Companion PR: https://github.com/irods/externals/pull/181

Cherry-picked from https://github.com/irods/irods_resource_plugin_s3/pull/2094
Cherry-picked from https://github.com/irods/irods_resource_plugin_s3/pull/2093

Leaving in draft for now because building the plugin doesn't quite work. Might need to do something in irods/externals first...

### CODE REVIEW

**Comment by korydraughn** [comment]
Should we wait to review this?

**Comment by alanking** [comment]
This can be reviewed now as it is nearly identical to #2094, just reserving the right to do some unannounced force-pushing :p

**Comment by korydraughn** [comment]
Will review as soon as i get an opening.

**Comment by alanking** [comment]
https://github.com/irods/externals/pull/181 is required along with the current set of changes in order to build the plugin. Will start running tests soon. Marking as ready for review since I do not expect to make any more dramatic changes outside of review comments.

**Comment by alanking** [comment]
When I tried to run tests for this, it seemed to be infinitely stuck and a lot of error messages were coming out of MinIO. Will need to investigate. Everything leading up to running the tests (including running the test hook) seems fine now.

**Comment by alanking** [comment]
A couple of things happened, preventing the tests from passing here:

1. Running two MinIO servers on the same host seems to be causing some problems when running tests in the testing environment. Not sure why this hasn't cropped up before, but it is causing problems now. I ran a single MinIO server and tests started running normally. As such, I created this issue to address these problems: #2101
2. A bug was discovered while trying to run my new tests in that an error is not being returned when copying data to S3 fails during sync-to-archive. @JustinKyleJames found the fix, which I've replicated in the latest commit. I am happy to drop that commit so he can get proper credit, but this set of changes causes tests to pass.

So... everything passes now, yay

**Comment by korydraughn** [comment]
> This can be reviewed now as it is nearly identical to #2094, just reserving the right to do some unannounced force-pushing :p

Is this PR still **nearly** identical to #2094? Is there anything we need to look at specifically since the new commits?

**Comment by alanking** [comment]
The only things that should be different at this point are the changes to the test hook to chown the keypair file (which is different because of python2) and the latest commit which addresses #2100 (which needs its commit message updated and/or @JustinKyleJames should make that change in a separate PR). So, it's still nearly identical save for those two things.

**Review by korydraughn — COMMENTED** [review]
Changes look good. Will await outcome with @JustinKyleJames regarding commit ownership before approving this PR.

**Comment by JustinKyleJames** [comment]
> Changes look good. Will await outcome with @JustinKyleJames regarding commit ownership before approving this PR.

Commit looks good and I think I am fine with the ownership being as is.

**Comment by alanking** [comment]
Thanks! Squashed and added coauthorship to that last commit.

**Review by korydraughn — APPROVED** [review]
Add the pounds!

**Comment by korydraughn** [comment]
Merge when ready.

**Pull request merged**
