### PR TITLE
bump version for 4.2.12.1

### PR DESCRIPTION
**Pull request by trel**
does line 8 also need to change from 1->0 ?

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
> does line 8 also need to change from 1->0 ?

Yes

**Comment by trel** [comment]
on it - thanks

**Comment by trel** [comment]
done

@JustinKyleJames tip of 4-2-stable passes tests I presume... ?

**Review by SwooshyCueb — APPROVED** [review]

**Review by korydraughn — APPROVED** [review]
Looks good to me.

**Comment by trel** [comment]
squashed - no #, because there's no issue... are we okay with that?   i feel it's not extremely necessary, but can do it, based on opinion here.

**Comment by korydraughn** [comment]
Are you asking whether we should pound and ship as is?

**Comment by trel** [comment]
i'm asking if you require an issue for me to #.  right now, there is no issue to attach this commit to.

**Comment by korydraughn** [comment]
Let's create an issue for this. We may want to tie it to something later on.

**Comment by trel** [comment]
done.  pounded.   ready for merge.

**Review by alanking — APPROVED** [review]

**Pull request merged**
