### PR TITLE
[2216] Updated README.md for troubleshooting checksum read request rate errors (main)

### PR DESCRIPTION
**Pull request by JustinKyleJames**
Cherry-picked from #2217.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good.

Pound it once irods/irods#7947 is resolved for the main branch of irods/irods.

**Review by alanking — APPROVED** [review]

**Comment by alanking** [comment]
Will merge this along with the PR which implements the actual feature in the iRODS server's main branch.

**Comment by alanking** [comment]
https://github.com/irods/irods/pull/7971 has been merged. I think we can # this.

**Comment by korydraughn** [comment]
Agreed.

**Comment by JustinKyleJames** [comment]
> [irods/irods#7971](https://github.com/irods/irods/pull/7971) has been merged. I think we can # this.

I added the pound.

**Pull request merged**
