### PR TITLE
[2112] give each minio instance its own data dir

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Comment by trel** [comment]
seems good.   the region name makes it sufficiently different/unique?

**Review by alanking — APPROVED** [review]
Pending @trel's question, looks good to me

**Comment by JustinKyleJames** [comment]
> seems good. the region name makes it sufficiently different/unique?

Yes it does.

**Comment by trel** [comment]
Good good.   please # when ready.

**Comment by JustinKyleJames** [comment]
> Good good. please # when ready.

Done

**Pull request merged**
