### PR TITLE
[irods/irods#6997] Add tests for Glacier-only objects (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Addresses irods/irods#6997

@JustinKyleJames - Can you please try this out for me? :)

### CODE REVIEW

**Comment by JustinKyleJames** [comment]
> Addresses [irods/irods#6997](https://github.com/irods/irods/issues/6997)
> 
> @JustinKyleJames - Can you please try this out for me? :)

Yes, I can.

**Comment by alanking** [comment]
Hmm... no indeed! I'll push a fix soon...

**Review by alanking — COMMENTED** [review]
@JustinKyleJames and I confirmed that these new tests pass when running against the changes made for irods/irods#7072

**Comment by korydraughn** [comment]
Are you saying this PR is good to merge once irods/irods#7072 is merged?

**Comment by alanking** [comment]
Yes, I think so.

**Comment by alanking** [comment]
irods/irods#7072 has been merged.

**Comment by alanking** [comment]
@JustinKyleJames and I ran the S3 tests together yesterday and found that they were passing

**Review by korydraughn — COMMENTED** [review]
Excellent.

Please squash to taste and leave off the pounds.

**Comment by alanking** [comment]
Squashed

**Review by korydraughn — APPROVED** [review]
Merge when ready.

**Pull request merged**
