### PR TITLE
Support multihosted/threaded/ranged S3 operations

### PR DESCRIPTION
**Pull request by earlephilhower**
Howdy Jason,

Due to the numerous commits I had in my fork, essentially refactoring everything, it was easier to re-branch from your HEAD and apply a single large diff commit.  Also makes the irods history nicer, less sausage making.

test_irods_resource_plugin_s3 and my own tests look good on this.  No actual additional tests need to be added to the suite as, by default, the suite will execute both single and multipart operations (based on file size).

You'll want to pull the latest libs3 *after* pull request 33 ( https://github.com/bji/libs3/pull/33 ) is merged.  There was a bug in multithreading I caught late last year, and there is a new bug introduced in January which causes random header corruption (single and multithreaded) that pull request 33 will fix.

I will close the prior pull request.

Commit message below...

Major rewrite to turn plugin into a multithreaded, high performance
consumer of S3 services and features from Amazon and third-party
object storage.

Enable multithreaded, multipart/multirange operation on S3 objects:
  Enables support of parallel upload and download of portions of large
  objects, which can significantly improve performance on both Amazon S3
  and other object stores.

  The number of parallel threads used can be configured with the parameter
    S3_MPU_THREADS=##  (default 10 threads)

  The MB per part to use for each portion of the object is configured with
    S3_MPU_CHUNK=##  (default 64, units in MB)

  For storing objects, multipart PUT is used.  For retreiving objects from
  the archive, multi-ranged HTTP GETs are performed.

Add S3_DEFAULT_HOSTNAME multiple host endpoint support:
  Add in multiple S3 host support.  Use a comma between host:ports to
  specify multiple hosts/ports to connect to in sequence (and in parallel
  when doing multipart uploads).  These hosts will be iterated over when
  connecting to the S3 service.
    S3_DEFAULT_HOSTNAME=ip1:port1,ip2:port2,ip3:port3;S3_AUTH_FILE=...

  Errors are logged to include the S3 host being used at the time of failed
  operations to help track down connecticity or other issues.

Add S3_SERVER_ENCRYPT=[0|1] to enable at-rest S3 encryption:
  This sets the flag to request that S3 store the object data in encrypted
  form on-disk.  This is NOT the same thing as HTTPS, and only affects the
  data at-rest.  IF you need encrypted communications to S3 as well as
  encryption of the object data once there, please be sure to specify
    ...;S3_PROTO=HTTPS;S3_SERVER_ENCRYPT=1;...
  on the resource definition line.

  Note also that this is not supported by some local S3 appliances or
  software.  When unsupported, the S3 server will return errors for all
  upload operations, logged in rodsLog.

Add S3_ENABLE_MD5 option to enable upload checksums on all PUTs:
  MD5 checksum calculations on all S3 PUT commands, setting the
  Content-MD5 header.

  Note that this requires reading each file effectively twice:  The
  first time the file is read to calculate the initial MD5 (because
  we need the MD5 to send the headers, we can't do this on the fly).
  Then the second time to actually send the file over the network to S3.

  If there is a MD5 mismatch it will be logged as an error by S3 and
  in rodsLog, and the iRODS system will be informed of archive failure.

Testing parameters to support out-of-CI testing:
  Add S3BUCKET and S3PARAMS environment overrides for resource test.
  By default use the hardcoded values in prior version for bucketname
  and the parameters (authentication, threads, proto, etc.).  If
  the environment variable S3BUCKET is set, overide the bucket we use,
  and if S3PARAMS are set override the entire resource configuration
  string.
  For example:
   S3BUCKET=user S3PARAMS='S3_DEFAULT_HOSTNAME=192.168.122.128:443;"\
   "S3_AUTH_FILE=/tmp/s3;S3_PROTO=HTTP;S3_RETRY_COUNT=15;S3_WAIT_TIME_SEC=1;"\
   "S3_MPU_THREADS=10;S3_MPU_CHUNK=16' "\
   python run_tests.py --run_specific_test test_irods_resource_plugin_s3

Add ERROR_INJECT testmode:
  Adds a -DERROR_INJECT compile-time option which will cause the specified
  call to pread or pwrite in a callback to fail.  This allows testing the
  retry/recovery mechanisms.

Removed dead/obsolete code, fix GCC -pedantic -Wall warnings:
  Clean up the code of most global variables, dead variables and functions,
  and GCC warnings in -pedantic mode.

Rework of error/retry handling, obey requested number of retries for all ops:
  All operations should now retry their operations on transient S3 errors,
  with the specified delay time and maximum retries.

### CODE REVIEW

**Comment by earlephilhower** [comment]
Howdy Jason,
Hope things are well on your end.  I’m sure it must be crazy with the 4.2 coming out, but wanted to ping you on the pull request.  I’ve got some rather epic business travel coming up in the next few weeks and doing any edits to fix merge conflicts on this lowest-of-low spec’d 13” dell laptop in a hotel room is not something I want to think about!
Thanks,
-EFP3

**Comment by jasoncoposky** [comment]
Thanks for the notice, I apriciate it.  We have been waiting for some PRs to make it into the upstream libs3 but at this point we need to move on.

I cloned a new repository, tried a local merge and using the command line instructions I built against 4.1.8.  g++ was not entirely happy, but either the code has moved or I did something wrong.

```
g++ -DRODS_SERVER -I/usr/include/irods/boost -I/usr/include/irods -I/usr/include/openssl  -O3 -fPIC -c -o .objs/libirods_s3.o libirods_s3.cpp
libirods_s3.cpp: In function ‘void mpuCancel(S3BucketContext*, const char*, const char*)’:
libirods_s3.cpp:1051:9: error: ‘S3AbortMultipartUploadHandler’ was not declared in this scope
         S3AbortMultipartUploadHandler abortHandler = { { mpuCancelRespPropCB, mpuCancelRespCompCB } };
         ^
libirods_s3.cpp:1059:67: error: ‘abortHandler’ was not declared in this scope
         S3_abort_multipart_upload(bucketContext, key, upload_id, &abortHandler);
                                                                   ^
libirods_s3.cpp:1059:79: error: ‘S3_abort_multipart_upload’ was not declared in this scope
         S3_abort_multipart_upload(bucketContext, key, upload_id, &abortHandler);
                                                                               ^
libirods_s3.cpp: In function ‘void mpuWorkerThread(void*)’:
libirods_s3.cpp:1121:159: error: ‘S3_upload_part’ was not declared in this scope
                 S3_upload_part(&bucketContext, g_mpuKey, putProps, &putObjectHandler, seq, g_mpuUploadId, partData.put_object_data.contentLength, 0, &partData);
                                                                                                                                                               ^
libirods_s3.cpp: In function ‘irods::error s3PutFile(const string&, const string&, rodsLong_t, const string&, const string&, irods::plugin_property_map&)’:
libirods_s3.cpp:1294:25: error: ‘S3MultipartInitialHandler’ was not declared in this scope
                         S3MultipartInitialHandler mpuInitialHandler = { {mpuInitRespPropCB, mpuInitRespCompCB }, mpuInitXmlCB };
                         ^
libirods_s3.cpp:1298:87: error: ‘mpuInitialHandler’ was not declared in this scope
                             S3_initiate_multipart(&bucketContext, key.c_str(), NULL, &mpuInitialHandler, NULL, &manager);
                                                                                       ^
libirods_s3.cpp:1298:120: error: ‘S3_initiate_multipart’ was not declared in this scope
                             S3_initiate_multipart(&bucketContext, key.c_str(), NULL, &mpuInitialHandler, NULL, &manager);
                                                                                                                        ^
libirods_s3.cpp:1381:29: error: ‘S3MultipartCommitHandler’ was not declared in this scope
                             S3MultipartCommitHandler commit_handler = { {mpuCommitRespPropCB, mpuCommitRespCompCB }, mpuCommitXmlCB, NULL };
                             ^
libirods_s3.cpp:1388:92: error: ‘commit_handler’ was not declared in this scope
                                 S3_complete_multipart_upload(&bucketContext, key.c_str(), &commit_handler, manager.upload_id, manager.remaining, NULL, &manager);
                                                                                            ^
libirods_s3.cpp:1388:160: error: ‘S3_complete_multipart_upload’ was not declared in this scope
                                 S3_complete_multipart_upload(&bucketContext, key.c_str(), &commit_handler, manager.upload_id, manager.remaining, NULL, &manager);
```

Thanks!

**Comment by earlephilhower** [comment]
Howdy,

You'll need to pull in the latest libs3 (https://github.com/bji/libs3) and make sure that it's built and installed as part of the irods-common.  The build is hardcoding it to pull in the local irods copy of thelib, so even if you installed the git head out of the irods tree it would built using /usr/include/irods/libs3.h and the private lib.a.  

There were a few bugs I found in libs3 from the last time you did a refresh (some header issues and multithreaded use of non-MT libc functions), IIRC, so I'd recommend just refreshing the libs3 clone in the irods repo and starting with a clean build. 

Thx

**Comment by jasoncoposky** [comment]
got it, makes sense.  since i installed the 4.1.8 development library its safe to assume I have the old libs3.

Thanks.

**Comment by earlephilhower** [comment]
Ping on this.  I hear it was in the CI.  Was all well or were any issues discovered?  Thx!

**Comment by adetorcy** [comment]
It passed the test suite against iRODS 4.1.8 and the latest libs3 code. Seeing some intermittent invalid signature errors against current iRODS 4-1-stable branch. Working on it.

**Comment by adetorcy** [comment]
Should we also be using bji/libs3/pull/44 for multi-part transfer?

**Comment by earlephilhower** [comment]
No, that actually is related to a bug I think you filed against Amazon S3 and large file renames, not uploads.  I just noticed it in the tracker a couple days ago and only had time this AM to dig into it.  On-prem doesn't have this issue, so since I'm using our own store it's not something I noticed.

Since the MP copy API didn't exist until, oh about 11AM today, the patch you're running does not implement MP copies.  :)

I'm looking into it realtime now, but do have other things to do before I leave for the UG meeting so I was going to submit an add'l patch after this one gets rolled in (after the UG so there's time to test/clean up/etc.)

It'd be much smaller than the existing one, so I'd like to get this one merged first and make my git tree cleaner and small changes like this easier to track.

**Comment by adetorcy** [comment]
Manually merged. See:
575a06c46c3d9bcecea521843bbcdd03dfc83990
fe6c7bc9ec8c3f0b55eda7c85d7669e64c67e788
efeae974e2184ddd9d02f9ccf8a381468b18121a
Thanks!

**Pull request closed without merging**
