### PR TITLE
Build fix cherry-picks (master)

### PR DESCRIPTION
**Pull request by alanking**
cherry-picked several things from 4-2-stable to match changes to build process

Awaiting confirmation that these changes are appropriate before #'ing

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
Commits 1, 3, and 4 are definitely in need of cherry-picking into master. I would imagine commit 2 is as well.

**Comment by alanking** [comment]
cherry-picked fix for #2000 provided by @JustinKyleJames 

Removed commit which removes the GCP test file as that change was reverted in 4-2-stable

**Comment by trel** [comment]
seems good.  please # em.

**Comment by alanking** [comment]
#'d

**Comment by alanking** [comment]
Sorry for extra push, I had to rebase. I realized that one of the commits was already in master

**Pull request merged**
