### PR TITLE
[#2080,#2154,irods/irods#7265] Minor reorganization + CMake TLC (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7265
Addresses #2080
Addresses #2154

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
Rebased and marked as ready for review

**Review by korydraughn — APPROVED** [review]
Didn't spot anything unusual.

Let's get one more approval before pounding.

**Review by alanking — APPROVED** [review]
Yep, looks identical to the other. # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
