### PR TITLE
[#2186] link `s3_transport_obj` to librt if librt has `shm_open` (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #2186

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes looks good. Will wait for your test results before approving.

**Comment by SwooshyCueb** [comment]
This does indeed fix building on centos 7.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
