### PR TITLE
[irods/irods#7263] CMake consistency sweep

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Changes look fine to me.

Let's give @JustinKyleJames and @alanking a chance to review this one before adding the pounds.

**Review by alanking — APPROVED** [review]
Yep, seems good. We will be bumping libs3 again soon once https://github.com/irods/libs3/pull/28 is merged, so putting it at latest is fine.

**Comment by korydraughn** [comment]
Add the pounds when ready.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
